akhq:
  connections:
    local:
      properties:
        bootstrap.servers: "kafka:9092"
      schema-registry:
        url: "http://schema-registry:8085"
      connect:
        - name: "connect"
          url: "http://connect:8083"
      ksqldb:
        - name: "ksqldb"
          url: "http://ksqldb:8088"

jpa:
  default:
    entity-scan:
      packages:
        - 'org.akhq.models.accessmanagement'
    properties:
      hibernate:
        hbm2ddl:
          auto: validate

datasources:
  default:
    url: jdbc:postgresql://postgres:5432/akhq
    username: akhq
    password: akhq
    driver-class-name: org.postgresql.Driver

flyway:
  datasources:
    default:
      enabled: true